Implement SingUpVC
Boslana/HH_School pull request #1
Opened 2023-11-06 13:18 UTC by Boslana

2023-11-09 10:59 UTC, irina-gs commented on ToDo/Classes/Modules/SignUp/SignUpViewController.swift
> +        navigationItem.title = L10n.SignUp.title
По дизайну в навигации не должно быть заголовка "Авторизация"

2023-11-09 11:17 UTC, irina-gs commented on ToDo/Resources/Storyboards/SignUp.storyboard
Цвет background для TextField должен быть #F1F1F1.
А цвет placeholder - #8C8C8C.

2023-11-09 11:29 UTC, irina-gs commented on ToDo/Classes/Modules/SignUp/SignUpViewController.swift
Нажатие на кнопку signUpButton должно приводить к главной странице.

2023-11-09 14:15 UTC, aps21 requested changes

2023-11-09 14:15 UTC, aps21 commented on ToDo/UIKit/TextField.swift
>          }))
перенос не нужен, влезает в 140 символов, обсудим на занятии

2023-11-09 14:15 UTC, aps21 commented on ToDo/UIKit/TextField.swift
> +        let button = UIButton(type: .custom, primaryAction: UIAction(handler: {[weak self] _ in self?.toggleSecureMode()
не хватает пробела (handler: { [

2023-11-09 14:15 UTC, aps21 commented on ToDo/Resources/Storyboards/SignUp.storyboard
пока что разрешила не юзать новосозданные филды

2023-11-10 06:48 UTC, merged

2023-11-10 09:47 UTC, aps21 commented on ToDo/Classes/Modules/SignUp/SignUpViewController.swift
> +    }
выравнивание уползло)

2023-11-10 09:48 UTC, aps21 commented on ToDo/UIKit/TextInput.swift
> +        return (textField.text == "" || textField.text == nil)
textField.text.isEmpty || textField.text == nil
можно без return и скобочек