Validation and button
Boslana/HH_School pull request #2
Opened 2023-11-13 16:02 UTC by Boslana

2023-11-15 23:03 UTC, tepaevayuliya commented on ToDo/UIKit/PrimaryButton.swift
> +                heightbgColor: .Color.primary.withAlphaComponent(0.5),
Название переменных тут должно быть скорее от слова "highlight", а не от "height". И в остальном коде тоже

2023-11-15 23:03 UTC, tepaevayuliya commented on ToDo/UIKit/PrimaryButton.swift
> +                insets: 22,
insets: 44

2023-11-15 23:03 UTC, tepaevayuliya commented on ToDo/UIKit/TextButton.swift
> +    }
Лучше добавить insets: 32, как в PrimaryButton.Mode.large (хотя по дизайну там вообще непонятно что нужно)

2023-11-15 23:03 UTC, tepaevayuliya commented on ToDo/Classes/Business/ValidationManager.swift
> +    static func isEmpty(commonText: String?) -> Bool {
Не особо понимаю смысл этой функции, так как есть системная функция isEmpty

2023-11-15 23:03 UTC, tepaevayuliya commented on ToDo/Classes/Modules/SignUp/SignUpViewController.swift
> +        }
Все конструкции if (эту и ниже, а также в файле AuthViewController.swift) можно заменить на if-else, чтобы в случае, когда поле уже пустое, не выполнять еще одну проверку на валидность (все равно выводим именно ошибку "Поле должно быть заполнено")

2023-11-16 07:14 UTC, Boslana commented on ToDo/Classes/Business/ValidationManager.swift
> +    static func isEmpty(commonText: String?) -> Bool {
я про нее забыла )

2023-11-16 10:48 UTC, aps21 requested changes

2023-11-16 10:48 UTC, aps21 commented on ToDo/Classes/Modules/Auth/AuthViewController.swift
> +        }
в теории у тебя тут лишнее выполнение кода
если поле пустое, то валидность на email оно не пройдет
и у тебя сначала выведется L10n.Validation.emptyTextField, а потом L10n.Validation.emptyTextField
упакуй в if {} else if {}

в регистрации аналогично

2023-11-16 10:48 UTC, aps21 commented on ToDo/Resources/L10n.swift
> +
лишняя строка

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/MainButton.swift
> -        configurationUpdateHandler = { [weak self] button in
молодец!

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/PrimaryButton.swift
> +                insets: 22,
у нас к исходной ширине кнопки прибавляется insets один раз
лучше написать 44

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextButton.swift
> +                font: .boldSystemFont(ofSize: 16),
инсеты?)

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextButton.swift
> +                height: 22,
22 - слишком мало, чтоб юзер смог нажать, давай сделаем 54

2023-11-16 12:26 UTC, merged