Add textView
Boslana/HH_School pull request #3
Opened 2023-11-13 17:24 UTC by Boslana

2023-11-16 01:44 UTC, tepaevayuliya commented on ToDo/UIKit/TextViewInput.swift
> +class TextViewInput: UIView, UITextViewDelegate {
final class

2023-11-16 01:44 UTC, tepaevayuliya commented on ToDo/UIKit/TextViewInput.swift
> +        }
Можно добавить invalidateIntrinsicContentSize(), чтобы переопределялся размер, иначе возникает баг при выполнении следующих действий:
1. Ввести многострочный текст в textView
2. Нажать кнопку, чтобы появилась ошибка под textView
3. Удалить несколько строчек текста из поля textView
![Simulator Screenshot - iPhone 15 Pro - 2023-11-16 at 03 07 03](https://github.com/Boslana/HH_School/assets/57157605/8f07c0a8-03ce-480f-b061-b0f0e2230fc9)

2023-11-16 01:44 UTC, tepaevayuliya commented on ToDo/UIKit/TextViewInput.swift
> +        var totalHeight = titleLabel.intrinsicContentSize.height + textView.frame.size.height + 8
вместо var можно использовать let

2023-11-16 10:48 UTC, aps21 commented
emailTextField.setup(titleText: L10n.Auth.emailTextFieldPlaceholder)
didTapSignIn - показываю ошибку emailTextField.show(error: "dwiodw\nuiheduwqhieuiuhwiuhi    2qhzmiu3ny9z137y")

https://github.com/Boslana/HH_School/assets/16414510/df500cc0-07fa-4836-ab42-e5b98fbf74f2

2023-11-16 10:48 UTC, aps21 requested changes

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +class TextViewInput: UIView, UITextViewDelegate {
final

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +        var totalHeight = titleLabel.intrinsicContentSize.height + textView.frame.size.height + 8
let - должен был быть варнинг

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +        errorLabel.bottomAnchor.constraint(equalTo: bottomAnchor)
выравнивание во всем файле - cmd + a, потом ctrl + i

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +            if constraint.firstAttribute == .height {
а если у тебя несколько констрейнтов на высоту?

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +                textView.isScrollEnabled = (newHeight == 200)
❤️
только скобочки лишние

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +        trailingAnchor.constraint(equalTo:errorLabel.trailingAnchor, constant: 8),
пробел equalTo: errorLabel

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +    private let paragraphStyle = NSMutableParagraphStyle()
зачем вынесла в отдельную переменную?

2023-11-16 10:48 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +        titleLabel.frame = CGRect(x: 0, y: 0, width: frame.width, height: 22)
сделала, потому что не на месте была?))
translatesAutoresizingMaskIntoConstraints = false
из-за этого сейчас уползает вправо))
на фреймах не верстаем

2023-11-17 09:54 UTC, aps21 requested changes

2023-11-17 09:54 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +    private var textViewHeightConstraint: NSLayoutConstraint?
почему не lazy var как выше?

2023-11-17 09:54 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +            textViewHeightConstraint!,
force unwrap - оч плохо, запрещаю))

2023-11-17 09:54 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +            trailingAnchor.constraint(equalTo:errorLabel.trailingAnchor, constant: 8),
пробел - equalTo: errorLabel

2023-11-17 09:54 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +        textViewHeightConstraint?.isActive = true
1. ты нигде не деактивируешь эту констрейнту
то есть ты в setup в NSLayoutConstraint.activate([... textViewHeightConstraint! ...]) - активируешь ее
затем в show(error: String) и hideError() снова зачем-то активируешь)
2. тут как раз надо трогать bottomContraint, а не высоту
зачем ты что-то делаешь с высотой текствью при появлении/скрывании ошибки?)

2023-11-18 07:35 UTC, merged