Feature/network and new item UI
Boslana/HH_School pull request #5
Opened 2023-11-28 08:12 UTC by Boslana

2023-11-29 18:02 UTC, aps21 requested changes
Комменты вчерашние, мб чего-то неактуально

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Auth/AuthViewController.swift
> +                    let alertVC = UIAlertController(title: "Ошибка!", message: error.localizedDescription, preferredStyle: .alert)
заголовок в локализацию, да и вообще давайте всю функцию вынесем в ParentViewController

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        checkmarkImageView.isHidden = !item.isCompleted
технически у тебя будет конфликтовать с isSelected
либо удали оттуда и всегда заполняй флаг с сервера
либо можно у коллекции после .reloadData() вызывать .selectItem(at: IndexPath(row: row, section: 0), animated: false, scrollPosition: [])

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +        collectionView.dataSource = self
можно настроить в сториборде

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +        }
❤️

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +            }
[вкусовщина]
в теории это надо настраивать только если у тебя пустая дата

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +        performSegue(withIdentifier: "new-item", sender: nil)
код повторяется дважды, давай вынесем в функцию

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +    @IBOutlet var createButton: PrimaryButton!
private

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                await loadToDos()
[недоработка тз]
еще можно обойтись без доп запроса, если успех, то тебе надо просто toggle значение isSelected

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/NewItem/NewItemViewController.swift
>  final class NewItemViewController: ParentViewController {
❤️

2023-11-29 18:02 UTC, aps21 commented on ToDo/Classes/Modules/SignUp/SignUpViewController.swift
> +                    let response = try await NetworkManager.shared.signUp(name: userNameTextField.text ?? "", email: emailTextField.text ?? "", password: passwordTextField.text ?? "")
давай вынесем всё в 64-ю строку
```
if isValidFlag, let name = userNameTextField.text, let ..., let ... else {
    return
}
```

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +        headers: [String: String]? = nil
❤️

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +        if let requestData = requestData, method != "GET" {
❤️
`if let requestData, method != "GET" {`

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +        headers?.forEach { request.setValue($1, forHTTPHeaderField: $0) }
❤️

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +        return try decoder.decode(DataResponse<Response>.self, from: data).data
❤️

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +        return
лишнее))

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +        UserDefaults.standard.set(authResponse.accessToken, forKey: "accessToken")
❤️

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +            requestData: EmptyRequest(),
без этой строки можно?

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/Request/ToDoRequestBody.swift
> +    let coordinate: CoordinateRequest
можно проинициализировать сразу, чтобы не тащить в код
```
let category: String = ""
let coordinate: Coordinate = Coordinate(longitude: "", latitude: "")
```

2023-11-29 18:02 UTC, aps21 commented on ToDo/Network/Responses/ToDoResponseBody.swift
> +    let coordinate: Coordinate
ненужные поля можно не объявлять

2023-11-29 18:02 UTC, aps21 commented on ToDo/UIKit/TextViewInput.swift
> +        }
выравнивание

2023-11-29 20:05 UTC, tepaevayuliya commented on ToDo/Classes/Modules/NewItem/NewItemViewController.swift
> +    @IBAction private func didTapCreateButton() {
Можно добавить проверку полей на пустоту, как мы делали при авторизации/регистрации

2023-11-29 20:05 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Main/MainViewController.swift
>          "Дедлайн: \(DateFormatter.dateFormate.string(from: deadlineDate))"
"Дедлайн: " можно вынести в локализацию

2023-11-29 20:05 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Main/MainViewController.swift
При загрузке экрана сначала показывает экран пустого состояния, а только потом (когда пришел ответ с сервера с данными о задачам) экран обновляется на экран с задачами. Можно добавить скрывание пустого состояния, пока не пришел ответ на запрос получения всех задач пользователя

2023-11-29 20:05 UTC, tepaevayuliya commented on ToDo/Network/NetworkManager.swift
> +    func createNewTodo(category: String, title: String, description: String, date: Date, coordinate: CoordinateRequest ) async throws -> TodoItemResponseBody {
Лишний пробельчик в конце параметров запроса

2023-11-30 06:02 UTC, Boslana commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        checkmarkImageView.isHidden = !item.isCompleted
если использовать второй вариант, то у меня ругается на row

2023-11-30 06:28 UTC, Boslana commented on ToDo/Network/NetworkManager.swift
> +            requestData: EmptyRequest(),
ругается (

2023-11-30 06:55 UTC, Boslana commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                await loadToDos()
+ обновлять ячейку?

2023-11-30 07:12 UTC, Boslana commented on ToDo/Classes/Modules/SignUp/SignUpViewController.swift
> +                    let response = try await NetworkManager.shared.signUp(name: userNameTextField.text ?? "", email: emailTextField.text ?? "", password: passwordTextField.text ?? "")
так? 
        if isValid, let name = userNameTextField.text, let email = emailTextField.text, let password = passwordTextField.text {
            Task {
                do {
                    let response = try await NetworkManager.shared.signUp(name: name , email: email , password: password )
                    log.debug("\(response.accessToken)")
                    let storyboard = UIStoryboard(name: "Main", bundle: nil)
                    let vc = storyboard.instantiateViewController(withIdentifier: "NavMainVC")
                    view.window?.rootViewController = vc
                } catch {
                    showAlert(title: L10n.NetworkErrorDescription.alertTitle, massage: error.localizedDescription)
                }
            }
        } else {
            return
        }

2023-11-30 08:33 UTC, aps21 commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        checkmarkImageView.isHidden = !item.isCompleted
расскажу на занятии)

2023-11-30 08:36 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                await loadToDos()
да, нужно будет и в data, и в ячейке
несколько вариантов для перезагрузки есть -
collectionView.reloadData()
collectionView.reloadSection(...)
collectionView.reloadItems(at: [IndexPath])
в общем если не забуду, то покажу на занятии

2023-11-30 08:38 UTC, aps21 commented on ToDo/Classes/Modules/SignUp/SignUpViewController.swift
> +                    let response = try await NetworkManager.shared.signUp(name: userNameTextField.text ?? "", email: emailTextField.text ?? "", password: passwordTextField.text ?? "")
let response = try await NetworkManager.shared.signUp(name: name , email: email , password: password ) - тут пробельчики лишние))

else {
            return
        } - вроде как не надо

2023-11-30 08:39 UTC, aps21 commented on ToDo/Network/NetworkManager.swift
> +            requestData: EmptyRequest(),
зачем передаешь EmptyRequest()? ты же не используешь тело в этом запросе

2023-12-01 13:45 UTC, merged