Complete Item Edit
Boslana/HH_School pull request #6
Opened 2023-12-05 06:43 UTC by Boslana

2023-12-05 18:42 UTC, irina-gs requested changes

2023-12-05 18:42 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
Думаю логичнее лоадер показывать только то время, когда обрабатывается запрос. Поэтому можно удалить эту строку и сразу устанавливать state

2023-12-05 18:42 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
Аналогично предыдущему комментарию

2023-12-05 18:42 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +    var id: String
Мне кажется лучше let. Он вроде бы нигде не должен меняться

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
Возможно, стоит убрать .now() + 2. Мы же это писали для видимости только

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Empty/EmptyViewController.swift
лишняя переменная @IBOutlet private var thirdSV: UIStackView!
кстати можно переделать экран на 3 стека

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Empty/EmptyViewController.swift
> +            lastSV.alignment = .center
можно удалить строки 38-39 и 54-55 (с lastSV), так как они делают одно и то же, а значит, ничего не меняется. Ну и само объявление lastSV тоже, раз мы уберем все связанное с ним

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        deadlineLabel.numberOfLines = 2
а нам точно нужны эти две линии? Вроде на мелких девайсах все помешается в одной линии

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        radioButton.setImage(UIImage.Main.radiobuttonDefault, for: .normal)
Может быть лучше вынести это в else в условии ниже? А то иначе получается, что сначала у нас все ячейки "невыполнены", а потом уже у части из них меняется картинка на "выполнены"

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        layer.masksToBounds = true
а нам точно нужны эти три строчки?

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Main/MainViewController.swift
>      var deadlineString: String {
А почему просто при выводе в ячейку не форматировать вместо того, чтобы создавать еще одну переменную для каждой ячейки?

2023-12-05 18:53 UTC, tepaevayuliya commented on ToDo/Classes/Modules/NewItem/NewItemViewController.swift
> +            navigationItem.rightBarButtonItem = nil
Вроде бы лишняя строка, потому что она по дефолту nil

2023-12-05 20:14 UTC, tepaevayuliya commented on ToDo/Classes/Modules/NewItem/NewItemViewController.swift
> +    override func viewWillDisappear(_ animated: Bool) {
о, так это чинит баг с клавиатурой, великолепно))

2023-12-06 10:25 UTC, Boslana commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.swift
> +        layer.masksToBounds = true
да, cornerRadius задает скругление, а masksToBounds = true обрезает все подслои внутри ячейки (но вроде как и без него все ок)

2023-12-06 10:59 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
>      var deadlineString: String {
по факту - это вычисляемая переменная, она не создается, это что-то вроде функции, код туда залезет только в момент использования
короч это норм

2023-12-06 11:18 UTC, aps21 requested changes

2023-12-06 11:18 UTC, aps21 commented on ToDo/Classes/Modules/Main/Cell/MainItemCell.xib
> +                                            <constraint firstAttribute="width" constant="24" id="OFf-Nj-56j"/>
на занятии расскажу про 44х44

2023-12-06 11:18 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +            self.data = todosResponse.map { MainDataItem(id: $0.id, title: $0.title, description: $0.description, deadlineDate: $0.date, isCompleted: $0.isCompleted) }
давай без map переделаем
TodoItemResponseBody и MainDataItem по факту одинаковые, юзай одну

2023-12-06 11:18 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +extension MainViewController: MainItemCellDelegate {
121 строка - лишняя пустая))

2023-12-06 11:18 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                collectionView.reloadItems(at: [indexPath])
хорошая тема с анимацией, но есть некие подводные камни
ты внутри этого блока захватываешь indexPath
но пока идет запрос на выполнение - юзер может добавить/удалить запись
и indexPath изменится
еще ты захватываешь selectedItem -> если юзер дважды нажмет на кнопку, то у тебя состояние изменится, хотя не должно)

на занятии планирую поднять вопрос обновления данных при отсутствии тз))

2023-12-06 19:49 UTC, aps21 approved these changes

2023-12-07 09:55 UTC, merged