Complete Profile and SneakBar
Boslana/HH_School pull request #7
Opened 2023-12-12 06:59 UTC by Boslana

2023-12-12 14:38 UTC, irina-gs requested changes

2023-12-12 14:38 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
В didSelectItemAt в default нужно добавить код, который в зависимости от selectedDate присваивает selectedItem правильную ячейку
Так как сейчас такой баг:

https://github.com/Boslana/HH_School/assets/78543273/93171cbd-b754-41c8-9f1c-d38e74516421

2023-12-12 14:38 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
Если после нажатия на radioButton на ячейке, нажать на кнопку Новая запись, то открывается экран редактирования, а не новой записи.

https://github.com/Boslana/HH_School/assets/78543273/00170afa-0fd4-4a31-bfc5-3812fa5807df

2023-12-12 15:43 UTC, irina-gs requested changes

2023-12-12 15:43 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                }
Мне кажется error не стоит приводить к типу NetworkError, так как в .empty(error: error) error должна быть типа Error. Из-за этого, например если не подключен интернет, не выходит экран с ошибкой No Connection, а постоянно отображается loader

2023-12-12 15:43 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                        self.showSnackbar(message: error.localizedDescription)
Здесь error типа NetworkError, и наверное из-за этого не отображается снек бар
И в аналогичных местах тоже самое

2023-12-13 15:10 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Parent/ParentViewController.swift
> +            snackbarLabel.topAnchor.constraint(equalTo: snackbarContainer.topAnchor, constant: 54),
Возможно стоит привязать константу к высоте статус бара, он вроде бы на разных девайсах немного отличается по высоте

2023-12-13 15:10 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Parent/ParentViewController.swift
> +        UserManager.shared.set(accessToken: nil)
Можно использовать функцию UserManager.shared.reset(), чтобы не писать (accessToken: nil)

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainDataCell/MainDateCell.swift
> +            titleLabel.textColor = isSelected ? UIColor.white : UIColor.black
стараемся не использовать системные цвета, берем только из ассетов

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                if let selectedDate = selectedDate, let selectedDateIndex = sections.firstIndex(where: { $0.date == selectedDate }) {
если название разворачиваемой переменной совпадает, то можно писать просто `if let selectedDate, ...`

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                    collectionView.selectItem(at: dateIndexPath, animated: false, scrollPosition: [])
🔥

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                    navigateToAuth()
в идеале вынести в одно место))

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                let response = try await NetworkManager.shared.profile()
не, давай запрос на профиль делать в профиле
а то юзеру ждать придется
да и он может нажать 100500 раз

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                    profileViewController.profile = response
а это, кстати, в prepare for segue

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                if let profileViewController = storyboard.instantiateViewController(withIdentifier: "ProfileVC") as? ProfileViewController {
переделай как с new-item

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                let currentYear = Calendar.current.component(.year, from: Date())
Calendar.current.isDate(<#T##date1: Date##Date#>, equalTo: <#T##Date#>, toGranularity: .year)

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +        }
🔥

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +        guard let selectedItem = selectedItem else {
лишнее  `= selectedItem`

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Parent/ParentViewController.swift
> +            snackbarLabel.topAnchor.constraint(equalTo: snackbarContainer.topAnchor, constant: 54),
надо будет использовать высоту статус бара, на se слишком большой отступ

2023-12-13 15:21 UTC, aps21 commented on ToDo/Classes/Modules/Parent/ParentViewController.swift
> +            UIView.animate(withDuration: 0.2, delay: duration, options: [], animations: {
классно, что с анимацией, и любопытное решение через delay))

2023-12-14 08:14 UTC, aps21 approved these changes

2023-12-14 08:18 UTC, merged