Implement ImagePicker, multipartFormData, PTR and loader
Boslana/HH_School pull request #8
Opened 2023-12-19 08:24 UTC by Boslana

2023-12-20 16:40 UTC, tepaevayuliya commented on ToDo/Classes/Modules/NewItem/NewItemViewController.swift
Если выбрать дату и открыть экран создания новой записи, то в календаре отображается дата/время первой записи в списке. Если дата не выбрана, то отображается текущая дата и время.

Не знаю баг это или специально сделанная фича)

https://github.com/Boslana/HH_School/assets/57157605/737c8a91-c3bc-45d9-b9ab-39ba8cbf772e

2023-12-20 16:40 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Profile/ProfileViewController.swift
Возможно стоит масштабировать картинку, если она не квадратная, чтобы не было обрезано по бокам
![image](https://github.com/Boslana/HH_School/assets/57157605/56953a77-ea3c-47cd-9f05-22f4072a75d2)

2023-12-20 16:40 UTC, tepaevayuliya commented on ToDo/Classes/Modules/Profile/ProfileViewController.swift
> +        let urlString = "http://45.144.64.179/api/user/photo/\(imageId)"
http://45.144.64.179 можно заменить на \(PlistFiles.apiBaseUrl)

2023-12-20 16:56 UTC, irina-gs requested changes

2023-12-20 16:56 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +    private func scrollToLastItem() {
Скролится до предпоследнего

2023-12-20 16:56 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +            } else if let newDate = date, let selectedDate, Calendar.current.isDate(selectedDate, inSameDayAs: newDate) {
Можно let newDate = date -> let date

2023-12-20 16:56 UTC, irina-gs commented on ToDo/Classes/Modules/Profile/ProfileViewController.swift
> +        let urlString = "http://45.144.64.179/api/user/photo/\(imageId)"
Можно http://45.144.64.179 записать как \\(PlistFiles.apiBaseUrl)

2023-12-20 16:56 UTC, irina-gs commented on ToDo/Network/NetworkManager.swift
> +            append(data)
Можно вынести в папку Extensions

2023-12-20 17:11 UTC, Boslana commented on ToDo/Classes/Modules/NewItem/NewItemViewController.swift
это была фича))

2023-12-22 14:39 UTC, Boslana commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +    private func scrollToLastItem() {
Перепроверила, у меня всегда до последнего скроллится.. хм 🧐

2023-12-22 15:09 UTC, irina-gs commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +    private func scrollToLastItem() {
У меня почему-то не скролится(

https://github.com/Boslana/HH_School/assets/78543273/3f493b1f-dae6-4b21-a03f-88ca575e455b

2023-12-22 15:27 UTC, aps21 requested changes

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +        collectionView.alwaysBounceVertical = true
❤️

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Auth/AuthViewController.swift
> +            signInButton.setLoading(true)
❤️

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +        let itemCount = collectionView.numberOfItems(inSection: 1)
❤️

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +
лишняя пустая строка

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Main/MainViewController.swift
> +                }
блин, код одинаковый, хочется объединить, но пока что не знаю как))
пропустим этот момент

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Parent/ParentViewController.swift
> +            snackbarContainer.topAnchor.constraint(equalTo: window?.topAnchor ?? view.topAnchor),
глупый вопрос
если window == nil, то у тебя снек не добавится никуда, констрейнты ко вью не крашнутся? 
давай мб развернем window через guard? иначе зачем вся логика, если снека не будет на экране))

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Profile/ProfileViewController.swift
> +            let fileName = (info[UIImagePickerController.InfoKey.imageURL] as? URL)?.lastPathComponent ?? "profile_photo.jpg"
❤️

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Profile/ProfileViewController.swift
> +                    _ = try await networkManager.uploadProfilePhoto(imageData: imageData, fileName: fileName)
нет никакой индикации, пользователю будет непонятно может ли он уходить с экрана

2023-12-22 15:27 UTC, aps21 commented on ToDo/Classes/Modules/Profile/ProfileViewController.swift
> +            return
в теории если нет профиля, то тоже можно ставить заглушку
```
avatarImageButton.kf.cancelImageDownloadTask()
avatarImageButton.setImage ... UIImage.Profile.profileAvatar
```

2023-12-22 15:27 UTC, aps21 commented on ToDo/UIKit/Button/PrimaryButton.swift
> +            loader.centerYAnchor.constraint(equalTo: centerYAnchor),
[слегка придирка]
если вдруг лоадер будет большой, а кнопка маленькая, то лоадер вылезет за пределы кнопки))
можно добавить lessThan/greaterThan констрейнты до кнопки

2023-12-24 13:45 UTC, merged